services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expenses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expenses_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql://user:password@db/expenses_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app           
      - /app/node_modules         
    ports:
      - "5173:5173"               
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data: